#### **1. What is the average TotalPayBenefits for each JobTitle? exclude ('Not Provided', 'Not provided')**

In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
conn = sql.connect('database.sqlite')
conn

In [3]:
pd.read_sql_query('select * from sqlite_master',conn)

,type,name,tbl_name,rootpage,sql
0,table,Salaries,Salaries,2,CREATE TABLE Salaries (\n Id INTEGER PRIMAR...
1,index,salaries_year_idx,Salaries,16566,CREATE INDEX salaries_year_idx ON Salaries (Year)

In [4]:
def sql_query(q):
    return pd.read_sql_query(q,conn)

In [5]:
q= 'select * from salaries'
sql_query(q)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,9999999.00,567595.43,2011,,San Francisco,
1,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
2,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
3,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
4,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602,8601,189082.74,,316285.74,316285.74,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148648,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148649,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148650,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [6]:
q = """SELECT JobTitle, AVG(TotalPayBenefits) AS AverageTotalPayBenefits
       FROM Salaries
       WHERE JobTitle != 'Not Provided'
       AND JobTitle != 'Not provided'
       GROUP BY JobTitle
"""
sql_query(q)

                                            JobTitle  AverageTotalPayBenefits
0                                      ACCOUNT CLERK             44035.664337
1                                         ACCOUNTANT             47429.268000
2                                  ACCOUNTANT INTERN             29031.742917
3                        ACPO,JuvP, Juv Prob (SFERS)             80266.370000
4                                      ACUPUNCTURIST             67594.400000
...                                              ...                      ...
2153                           X-RAY LABORATORY AIDE             52705.880385
2154                           X-Ray Laboratory Aide             69521.123200
2155  YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS             53632.870000
2156                              Youth Comm Advisor             60118.550000
2157                                     ZOO CURATOR             66686.560000

[2158 rows x 2 columns]

#### **2. Show The JobTitle and Overtime Pay for All Employees With Overtime Pay greater than 50000**

In [7]:
q="""select JobTitle , OvertimePay from Salaries
  where OvertimePay>50000
"""
sql_query(q)

                                              JobTitle   OvertimePay
0                      CAPTAIN III (POLICE DEPARTMENT)     106088.18
1                 WIRE ROPE CABLE MAINTENANCE MECHANIC      56120.71
2                   BATTALION CHIEF, (FIRE DEPARTMENT)       89062.9
3                   BATTALION CHIEF, (FIRE DEPARTMENT)      86362.68
4     ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)      71344.88
...                                                ...           ...
2163                           Parking Control Officer      54738.36
2164                                      Not provided  Not Provided
2165                                      Not provided  Not Provided
2166                                      Not provided  Not Provided
2167                                      Not provided  Not Provided

[2168 rows x 2 columns]

#### **3. What is the total number of unique employees? exclude ('Not Provided', 'Not provided')**

In [8]:
q = """
SELECT COUNT(DISTINCT EmployeeName)
FROM Salaries
WHERE EmployeeName != 'Not Provided'
AND EmployeeName != 'Not provided'
"""
sql_query(q)

   COUNT(DISTINCT EmployeeName)
0                        110808

#### **4.Show The Top 10 highest Paid Employees**

In [9]:
q = """SELECT EmployeeName, TotalPay
       FROM Salaries
       ORDER BY TotalPay DESC
       LIMIT 10"""

sql_query(q)

           EmployeeName    TotalPay
0        NATHANIEL FORD  9999999.00
1           David Shinn   471952.64
2            Amy P Hart   390111.98
3        Gary Altenberg   362844.66
4         John Goldberg   350403.41
5           Samson  Lai   347102.32
6       Ellen G Moffatt   344187.46
7  William J Coaker Jr.   339653.70
8        Gregory P Suhr   339282.07
9     Frederick Binkley   337204.86

#### **5.Show All Employees Ordered By Their TotalPay Benefits In Descending Order**

In [10]:
q = '''SELECT EmployeeName, TotalPayBenefits
       FROM Salaries
       ORDER BY TotalPayBenefits DESC'''

sql_query(q)

                EmployeeName  TotalPayBenefits
0             NATHANIEL FORD         567595.43
1                David Shinn         510732.68
2                 Amy P Hart         479652.21
3       William J Coaker Jr.         436224.36
4             Gregory P Suhr         425815.28
...                      ...               ...
148648          Not provided              0.00
148649      Timothy E Gibson             -2.73
148650        Mark E Laherty             -8.20
148651         David P Kucia            -33.89
148652             Joe Lopez           -618.13

[148653 rows x 2 columns]